/* Generated by the Nim Compiler v0.19.9 */
/*   (c) 2018 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var nim_program_result = 0;
var global_raise_hook_355418 = [null];
var local_raise_hook_355423 = [null];
var out_of_mem_hook_355426 = [null];
  if (!Math.trunc) {
    Math.trunc = function(v) {
      v = +v;
      if (!isFinite(v)) return v;

      return (v - v % 1)   ||   (v < 0 ? -0 : v === 0 ? v : 0);
    };
  }
var object_id_473237 = [0];
async function HEX3Aanonymous_488046(event_488048, context_488049) {

		function inner_488118() {
			var result_488120 = null;

			var F={procname:":anonymous.inner",prev:framePtr,filename:"../../../../../usr_local/apps/6/nim/devel/lib/js/jsffi.nim",line:0};
			framePtr = F;
			BeforeRet: do {
				F.line = 430;
				var a_488121 = null;
				F.line = 431;
				a_488121 = {};
				F.line = 441;
				a_488121.statusCode = 200;
				F.line = 441;
				a_488121.body = "";
				F.line = 450;
				result_488120 = a_488121;
				break BeforeRet;
			} while (false);
			framePtr = F.prev;

			return result_488120;

		}

	var result_488059 = null;

	var F={procname:"hello_fetch_wip.:anonymous",prev:framePtr,filename:"hello_fetch_wip.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		F.line = 17;
		var resp_488091 = https_488017.get(("https://08ad1pao69.execute-api.us-east-1.amazonaws.com/dev/random_joke"));
		F.line = 19;
		console.log((resp_488091));
		F.line = 21;
		result_488059 = inner_488118();
		break BeforeRet;
	} while (false);
	framePtr = F.prev;

	return result_488059;

}
var https_488017 = require("https");
exports.handler = HEX3Aanonymous_488046;
