/* Generated by the Nim Compiler v0.19.9 */
/*   (c) 2018 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var nim_program_result = 0;
var global_raise_hook_355418 = [null];
var local_raise_hook_355423 = [null];
var out_of_mem_hook_355426 = [null];
  if (!Math.trunc) {
    Math.trunc = function(v) {
      v = +v;
      if (!isFinite(v)) return v;

      return (v - v % 1)   ||   (v < 0 ? -0 : v === 0 ? v : 0);
    };
  }
var object_id_473237 = [0];
async function HEX3Aanonymous_488043(event_488045, context_488046) {

		function inner_488084() {
			var result_488086 = null;

			var F={procname:":anonymous.inner",prev:framePtr,filename:"../../../../../usr_local/apps/6/nim/devel/lib/js/jsffi.nim",line:0};
			framePtr = F;
			BeforeRet: do {
				F.line = 430;
				var a_488087 = null;
				F.line = 431;
				a_488087 = {};
				F.line = 441;
				a_488087.statusCode = 200;
				F.line = 441;
				a_488087.body = "Hello, World! From Nim.";
				F.line = 450;
				result_488086 = a_488087;
				break BeforeRet;
			} while (false);
			framePtr = F.prev;

			return result_488086;

		}

	var result_488056 = null;

	var F={procname:"hello_async.:anonymous",prev:framePtr,filename:"hello_async.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		F.line = 8;
		result_488056 = inner_488084();
		break BeforeRet;
	} while (false);
	framePtr = F.prev;

	return result_488056;

}
exports.handler = HEX3Aanonymous_488043;
