/* Generated by the Nim Compiler v0.19.1 */
/*   (c) 2018 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var nimvm_312578 = false;
var nim_program_result = 0;
var global_raise_hook_318818 = [null];
var local_raise_hook_318823 = [null];
var out_of_mem_hook_318826 = [null];
  if (!Math.trunc) {
    Math.trunc = function(v) {
      v = +v;
      if (!isFinite(v)) return v;

      return (v - v % 1)   ||   (v < 0 ? -0 : v === 0 ? v : 0);
    };
  }
var object_id_446245 = [0];

function HEX3Aanonymous_462057(event_462059, context_462060, callback_462065) {

		function inner_462115() {
			var result_462117 = null;

			var F={procname:":anonymous.inner",prev:framePtr,filename:"../../../../../stow/pkgs/nim/devel/lib/js/jsffi.nim",line:0};
			framePtr = F;
			BeforeRet: do {
				F.line = 423;
				var a_462118 = null;
				F.line = 424;
				a_462118 = {};
				F.line = 434;
				a_462118.statusCode = 200;
				F.line = 434;
				a_462118.body = "Hello, World! From Nim.";
				F.line = 443;
				result_462117 = a_462118;
				break BeforeRet;
			} while (false);
			framePtr = F.prev;

			return result_462117;

		}

	var F={procname:"hello.:anonymous",prev:framePtr,filename:"hello.nim",line:0};
	framePtr = F;
		console.log(("Hello3"));
		console.log(("Hello4"));
		F.line = 15;
		callback_462065(null, inner_462115());
	framePtr = F.prev;

	
}
console.log(("Hello1"));
console.log(("Hello2"));
exports.handler = HEX3Aanonymous_462057;
