/* Generated by the Nim Compiler v0.19.1 */
/*   (c) 2018 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var nimvm_150578 = false;
var nim_program_result = 0;
var global_raise_hook_157018 = [null];
var local_raise_hook_157023 = [null];
var out_of_mem_hook_157026 = [null];
  if (!Math.trunc) {
    Math.trunc = function(v) {
      v = +v;
      if (!isFinite(v)) return v;

      return (v - v % 1)   ||   (v < 0 ? -0 : v === 0 ? v : 0);
    };
  }
var object_id_284245 = [0];
async function HEX3Aanonymous_301058(event_301060, context_301061) {

		function inner_301147() {
			var result_301149 = null;

			var F={procname:":anonymous.inner",prev:framePtr,filename:"../../../../../stow/pkgs/nim/devel/lib/js/jsffi.nim",line:0};
			framePtr = F;
			BeforeRet: do {
				F.line = 423;
				var a_301150 = null;
				F.line = 424;
				a_301150 = {};
				F.line = 434;
				a_301150.statusCode = 200;
				F.line = 434;
				a_301150.body = "";
				F.line = 443;
				result_301149 = a_301150;
				break BeforeRet;
			} while (false);
			framePtr = F.prev;

			return result_301149;

		}

	var result_301072 = null;

	var F={procname:"hello_fetch.:anonymous",prev:framePtr,filename:"hello_fetch.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		F.line = 16;
		var resp_301111 = https_301017.get(("https://08ad1pao69.execute-api.us-east-1.amazonaws.com/dev/random_joke"));
		console.log((resp_301111));
		F.line = 20;
		result_301072 = inner_301147();
		break BeforeRet;
	} while (false);
	framePtr = F.prev;

	return result_301072;

}
var https_301017 = require("https");
exports.handler = HEX3Aanonymous_301058;
