/* Generated by the Nim Compiler v0.19.1 */
/*   (c) 2018 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var nimvm_169578 = false;
var nim_program_result = 0;
var global_raise_hook_175818 = [null];
var local_raise_hook_175823 = [null];
var out_of_mem_hook_175826 = [null];
  if (!Math.trunc) {
    Math.trunc = function(v) {
      v = +v;
      if (!isFinite(v)) return v;

      return (v - v % 1)   ||   (v < 0 ? -0 : v === 0 ? v : 0);
    };
  }
var object_id_303245 = [0];

function HEX3Aanonymous_319015(event_319017, context_319018, callback_319023) {

		function inner_319045() {
			var result_319047 = null;

			var F={procname:":anonymous.inner",prev:framePtr,filename:"../../../../../stow/pkgs/nim/devel/lib/js/jsffi.nim",line:0};
			framePtr = F;
			BeforeRet: do {
				F.line = 423;
				var a_319048 = null;
				F.line = 424;
				a_319048 = {};
				F.line = 434;
				a_319048.statusCode = 200;
				F.line = 434;
				a_319048.body = "Hello, World";
				F.line = 443;
				result_319047 = a_319048;
				break BeforeRet;
			} while (false);
			framePtr = F.prev;

			return result_319047;

		}

	var F={procname:"hello.:anonymous",prev:framePtr,filename:"hello.nim",line:0};
	framePtr = F;
		F.line = 5;
		callback_319023(null, inner_319045());
	framePtr = F.prev;

	
}
exports.handler = HEX3Aanonymous_319015;
