/* Generated by the Nim Compiler v0.19.1 */
/*   (c) 2018 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var nimvm_312578 = false;
var nim_program_result = 0;
var global_raise_hook_318818 = [null];
var local_raise_hook_318823 = [null];
var out_of_mem_hook_318826 = [null];
  if (!Math.trunc) {
    Math.trunc = function(v) {
      v = +v;
      if (!isFinite(v)) return v;

      return (v - v % 1)   ||   (v < 0 ? -0 : v === 0 ? v : 0);
    };
  }
var object_id_446245 = [0];
async function HEX3Aanonymous_463055(event_463057, context_463058) {

		function inner_463129() {
			var result_463131 = null;

			var F={procname:":anonymous.inner",prev:framePtr,filename:"../../../../../stow/pkgs/nim/devel/lib/js/jsffi.nim",line:0};
			framePtr = F;
			BeforeRet: do {
				F.line = 423;
				var a_463132 = null;
				F.line = 424;
				a_463132 = {};
				F.line = 434;
				a_463132.statusCode = 200;
				F.line = 434;
				a_463132.body = (("Hello, " + name_463107) + "! From Nim.");
				F.line = 443;
				result_463131 = a_463132;
				break BeforeRet;
			} while (false);
			framePtr = F.prev;

			return result_463131;

		}

	var result_463069 = null;

	var F={procname:"hello_name_cstring.:anonymous",prev:framePtr,filename:"hello_name_cstring.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		F.line = 9;
		var name_463107 = (event_463057.queryStringParameters.name);
		if ((name_463107 == "")) {
		F.line = 11;
		name_463107 = "World";
		}
		
		F.line = 13;
		result_463069 = inner_463129();
		break BeforeRet;
	} while (false);
	framePtr = F.prev;

	return result_463069;

}
exports.handler = HEX3Aanonymous_463055;
